auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka:9092
    metrics:
      port: 9092
      type: JMX
    name: local
    properties: {}
    readOnly: false
    schemaRegistry: http://localhost:8080
    schemaRegistryAuth:
      password: password
      username: username
rbac:
  roles: []
webclient: {}
